### ISSUE TITLE
关于baseline的设置的疑问

### ISSUE THREAD

**Issue by DJEddyking** [WentaoTan/Interleaved-Learning#2]
您好，我拜读了您的论文，发现论文中对于baseline的设置描述较少。
我有个疑问，baseline是直接采用memory-based的分类器训练一个单网络结构，即，一次前向一次反向。还是说，只是去掉了DBS模块，仍然对memory bank的域平均特征更新，即，FBF方式训练？因为我自己采用balanced base方法的baseline，D+C3+MS --> M只能达到54左右的mAP，80左右的rank-1。

**Comment by WentaoTan** [comment]
您好！我们文章的baseline是FBF，第二次F的输出特征用来更新Memory。
希望能够帮到您！

**Comment by DJEddyking** [comment]
> 

好的，谢谢
