### ISSUE TITLE
关于对比公平问题

### ISSUE THREAD

**Issue by pSGAme** [WentaoTan/Interleaved-Learning#4]
您好，首先感谢您出色的工作！

据我所知 您自己的工作 和 您复现的其他人的工作 的设置 是把源域的训练集和测试集都拿来训练，但是其他方法除了RaMoE, 训练的时候并没有把测试集拿来训练。 所以结果表是否要更新一下?

**Comment by WentaoTan** [comment]
您好，七夕节快乐！

我们注意到有些工作包含多个setting，其中一些训练时仅使用train set，一些训练时使用train set + test set。
比如M3L没有使用后面的setting；META，ACL则是两者都有。
为了公平比较，我们重现了cvpr21年以后的文章（开源的），以确保数据的正确性。 
在此之前的文章大多援引report的性能，我们将仔细检查这些数据，如果有更新会及时注明。 
最后如果您能指引我们具体是哪些数据有误，我们将感激不尽！ 

谢谢！

**Comment by pSGAme** [comment]
是的， DG-ReID 的setting 设置过于五花八门了， 有的文章又不说清楚，很难受。我看到你前面表格引用的很多数据其实和MECL的很像，MECL的应该是只用train set的。  就是我看的文章里面，用了全部的好像就一个RaMoE, 和 AAAI2022的GDNorm。
不管怎么样感谢您的工作，特别是mixstle 和 DSU 这种写的很清楚，很受用。

**Comment by pSGAme** [comment]
此外，那篇AAAI2022 GDNorm 和M3L对比的时候也是很不公平的。 所以现在的设置太乱了，真希望有个大牛可以统一一下，不然一直要和审稿人扯嘴皮子。
