### ISSUE TITLE
关于ibn-net

### ISSUE THREAD

**Issue by pSGAme** [WentaoTan/Interleaved-Learning#5]
作者你好，请问你们有在ibn-net上测试过吗？结果如何呢？ 还有就是我注意到你们把源域的测试集都是拿来训练了，另一种没有源域测试集的结果你们有吗？ 我看ACL和META都有。

**Comment by WentaoTan** [comment]
（1）ResNet50-ibn没有试过，但是ACL backbone是基于ResNet50-ibn的，我们在ACL上面试了如文章的性能。
（2）仅用源域的train set的实验做过也是有效果的。我们因为有很多其他的实验就没有将其列举在文中。
